### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Ben",
  "email": "ben@test.com",
  "password": "password",
  "password_confirmation": "password",
  "group_id": 1
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@test.com",
  "password": "password"
}

###
GEt http://localhost:3000/restaurants.json

###
POST http://localhost:3000/restaurants.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTA2NDUwNjd9.88lzIdfWfx_WNyK1c0Lygjr3c73pGGE8RKq2r4hlblM
content-type: application/json

{
  "name": "BJ's Brewhouse",
  "cuisines": "American",
  "address": "8273 Brews Dr.",
  "image": "https://cloudfront.bjsrestaurants.com/img_5e4c874ee9b0a8.33886308_502_Colorado%20Springs_2019.jpg"
}