@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM3OTIxMTR9.GjZecACChjZF4a_kdnw03eNRhHNFF6HqJ9o9bQmf0S8

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": "",
  "password_confirmation": "",
  "group_id": 
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jimmy@email.com",
  "password": "password"
}

###
GET http://localhost:3000/users/1.json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3000/restaurants.json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3000/restaurants/search.json
Authorization: Bearer {{jwt}}

###
POST http://localhost:3000/restaurants/search.json
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "currentCity": "Colorado Springs"
}

###
POST http://localhost:3000/restaurants.json
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "name": "Wok In Wok Out",
  "cuisines": "Chinese",
  "address": "539 Oro Blanco",
  "image": "https://media-cdn.tripadvisor.com/media/photo-s/0c/ba/7e/26/entrance-of-wok-in-wok.jpg"
}

###
GET http://localhost:3000/users/group.json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3000/groups.json

###
POST http://localhost:3000/vote_restaurants
Authorization: Bearer {{jwt}}

###
PATCH http://localhost:3000/vote_restaurants
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "id": 1
}

###
GET http://localhost:3000/vote_restaurants.json
Authorization: Bearer {{jwt}}